
name: Run selenium tests

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build-jar-job:
    name: 'Run selenium tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: 'Run with Maven'
        run:  mvn install surefire:test
